# Generated by Django 5.1.1 on 2024-10-02 18:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^0[0-9]{9}$')])),
                ('is_admin', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('national_id', models.IntegerField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid national ID.', regex='\\d{10}')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
