# Generated by Django 5.1.1 on 2024-10-02 18:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='national_id',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid national ID.', regex='\\d{10}')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid phone number.', regex='^0[0-9]{9}$')]),
        ),
    ]
