# Generated by Django 5.1.1 on 2024-10-08 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_wallet_balance'),
        ('videos', '0007_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='subscription_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='videos.subscription'),
        ),
    ]
