# Generated by Django 5.1.1 on 2024-10-07 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_history_rating_video_is_subscription_needed_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='director_id',
        ),
        migrations.AddField(
            model_name='video',
            name='director_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='videos.director'),
        ),
    ]
