# Generated by Django 5.1.1 on 2024-10-07 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_remove_video_director_id_video_director_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='director_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='videos.director'),
        ),
    ]
