# Generated by Django 5.1.1 on 2024-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_alter_subscription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='watch_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
