# Generated by Django 5.1.1 on 2024-10-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_alter_subscription_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
